---
- name: Enable nested KVM
  copy: dest=/etc/modprobe.d/kvm-intel.conf content="options kvm-intel nested=1\n"

- name: Install libvirt
  apt: pkg="{{ item }}" install_recommends=no state=latest
  with_items:
  - libvirt-daemon-system
  - qemu-kvm
  - qemu-block-extra
  - bridge-utils
  - tcpdump
  - kpartx
  - python-libvirt
  - python-lxml

- name: Auto suspend guests on shutdown
  lineinfile: dest=/etc/default/libvirt-guests
              line="ON_SHUTDOWN=suspend"

- name: Remove default net
  virt_net: name=default state=absent
