---
- name: Install Ceph monitor and manager
  apt: pkg={{ item }}
  with_items:
  - ceph-mon
  - ceph-mgr

- name: Gather admin keyring
  command: ceph auth get client.admin
  run_once: true
  register: auth_keyring_result

- name: Install Admin keyring
  copy: content="{{ auth_keyring_result.stdout }}\n"
        dest=/etc/ceph/ceph.client.admin.keyring mode=0600
