---
- name: Install iptables-persistent
  apt: pkg=iptables-persistent

- name: IPv4 Firewall rules
  template: src=rules.v4 dest=/etc/iptables/rules.v4
  notify:
  - restore-iptables-rules

- name: IPv6 Firewall rules
  template: src=rules.v6 dest=/etc/iptables/rules.v6
  notify:
  - restore-ip6tables-rules
