---
- name: install ntp
  apt: pkg=ntp

- name: Remove all NTP pools
  lineinfile: dest=/etc/ntp.conf regexp='^pool ' state=absent
  notify:
  - restart-ntp

- name: Add NTP server
  lineinfile: dest=/etc/ntp.conf regexp='^server ' line="server {{ ntp_servers | first }}"
  notify:
  - restart-ntp
